{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smart-collab-gallery
  namespace: "prometheus"
  labels:
    release: "prometheus"
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: smart-collab-gallery
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: "http"
    interval: {{ .Values.serviceMonitor.interval }}
    path: {{ .Values.serviceMonitor.path }}
{{- end -}}