apiVersion: v1
kind: Service
metadata:
  name: smart-collab-gallery
  namespace: {{ .Release.Namespace }}
  labels:
    app: scene-api
spec:
  type: ClusterIP
  selector:
    app: smart-collab-gallery
  ports:
    - name: grpc
      protocol: TCP
      port: 9000
      targetPort: p-9000
    - name: http
      protocol: TCP
      port: 8000
      targetPort: p-8000
