apiVersion: v1
kind: Service
metadata:
  name: scene-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: scene-api
spec:
  type: ClusterIP
  selector:
    app: scene-api
  ports:
    - name: grpc
      protocol: TCP
      port: 9000
      targetPort: p-9000
    - name: http
      protocol: TCP
      port: 8000
      targetPort: p-8000
