hpa:
  cpuUtilization: 80
  maxReplicas: 3
  memoryUtilization: 80
  minReplicas: 1
sceneApi:
  env: test
  region: us
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 51m
      memory: 37Mi
  version: 4
serviceMonitor:
  enabled: true
  interval: 15s
  path: /metrics